testTS: 
	g++ testTeacherStudent.cpp Person.cpp Student.cpp Teacher.cpp GradeRestriction.cpp UsedToBeStudent.cpp Distributor.cpp
	./a.out
	
testSimple: 
	g++ clientTest.cpp Person.cpp Student.cpp Teacher.cpp GradeRestriction.cpp UsedToBeStudent.cpp Distributor.cpp
	./a.out
	
run:
	./a.out
bla:
	echo "BBB"
